name: Update Annotations QC

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Get VH Pipeline Details
      id: getLatestVHPipeline
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://app.valohai.com/api/v0/pipelines/?project=017d9b49-9e46-865d-07dd-82c4c6e2eb29&ordering=-ctime&limit=1'
        method: 'GET'
        customHeaders: '{"Authorization": "Token uWWnzXsWLEPITvMqKCGUGARuSP2RwL9kg5xYd94l"}'
        data: '{"limit": "1", "project": "017d9b49-9e46-865d-07dd-82c4c6e2eb29", "pipeline": "generate-dataset-train-evaluate-predict"}'
    - name: Show Result
      run: |
        echo ${{ fromJson(steps.getLatestVHPipeline.outputs.response) }}
